version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
      target: deps
    command: yarn start
    volumes:
      - ./public:/app/public
      - ./src:/app/src
    ports:
      - 3000:3000
